myapp/urls.py
from.views import *
from django.urls import path

urlpatterns = [
    path('', custom_login, name='login'),
    path('home',home, name='home'),
    path('index',index,name="index"),

    path('property-profile/<int:property_id>/', property_profile, name='property_profile'),
    path('tenant-management', tenant_management, name='tenant_management'),
    path('tenant-profile/<int:tenant_id>/', tenant_profile, name='tenant_profile'),

]

mypro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    USERNAME_FIELD="email"
    REQUIRED_FIELDS=('username',)

    def __str__(self):
        return self.username
class Property(models.Model):
    name = models.CharField(max_length=255)
    address = models.TextField()
    location = models.CharField(max_length=255)
    features = models.TextField()

class Unit(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    rent_cost = models.DecimalField(max_digits=10, decimal_places=2)
    unit_type_choices = [
        ('1BHK', '1BHK'),
        ('2BHK', '2BHK'),
        ('3BHK', '3BHK'),
        ('4BHK', '4BHK'),
    ]
    unit_type = models.CharField(max_length=4, choices=unit_type_choices)

class Tenant(models.Model):
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    address = models.TextField()
    document_proofs = models.TextField()
    agreement_end_date = models.DateField()
    monthly_rent_date = models.IntegerField()

myapp/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.shortcuts import render
from .models import Property, Unit, Tenant

def property_profile(request, property_id):
    property_obj = Property.objects.get(pk=property_id)
    units = Unit.objects.filter(property=property_obj)
    tenants = Tenant.objects.filter(unit__property=property_obj)
    return render(request, 'property_profile.html', {'property': property_obj, 'units': units, 'tenants': tenants})

def tenant_management(request):
    tenants = Tenant.objects.all()
    return render(request, 'tenant_management.html', {'tenants': tenants})

def tenant_profile(request, tenant_id):
    tenant_obj = Tenant.objects.get(pk=tenant_id)
    return render(request, 'tenant_profile.html', {'tenant': tenant_obj})
def custom_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, f'Welcome back, {user.username}!')
                return redirect('home') 
            else:
                messages.error(request, 'Invalid email or password. Please try again.')
    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {'form': form})
def home(request):
    return render(request,'Home.html')
def index(request):
    return render(request,'index.html')

myapp/templates/Home.html
1  <h1>Home</h1>
2  <hr>
<a href="{% url 'tenant_management' %}">Tenant-Management</a>

myapp/templates/index.html
<!DOCTYPE html>
<html lang="en">

    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">   
   
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
 
     <!-- Site Metas -->
    <title>CITY Real Estate - Responsive HTML5 Landing Page Template</title>  
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="../static/images/favicon.ico" type="image/x-icon" />
    <link rel="apple-touch-icon" href="../static/images/apple-touch-icon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
    <!-- Site CSS -->
    <link rel="stylesheet" href="../static/style.css">
    <!-- Colors CSS -->
    <link rel="stylesheet" href="../static/css/colors.css">
    <!-- ALL VERSION CSS -->
    <link rel="stylesheet" href="../static/css/versions.css">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="../static/css/responsive.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="../static/css/custom.css">

    <!-- Modernizer for Portfolio -->
    <script src="../static//js/modernizer.js"></script>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body class="realestate_version">

    <!-- LOADER -->
    <div id="preloader">
        <span class="loader"><span class="loader-inner"></span></span>
    </div><!-- end loader -->

    <div class="parallax first-section">
        <div class="container">
            <div class="row">
                <div class="col-md-6 wow slideInLeft hidden-xs hidden-sm">
                    <div class="contact_form">
                        <h3><i class="fa fa-envelope-o grd1 global-radius"></i> QUICK APPOINTMENT</h3>
                        <form method="post" action="{% url 'login' %}">
                            {% csrf_token %}
                            {{ form.username.label_tag }}
                            {{ form.username }}
                            {{ form.password.label_tag }}
                            {{ form.password }}
                            <button type="submit">Login</button>
                        </form>
                    </div>
                </div>

    <a href="#" id="scroll-to-top" class="dmtop global-radius"><i class="fa fa-angle-up"></i></a>

    <!-- ALL JS FILES -->
    <script src="../static/js/all.js"></script>
    <!-- ALL PLUGINS -->
    <script src="../static/js/custom.js"></script>
    <script src="../static/js/portfolio.js"></script>
    <script src="../static/js/hoverdir.js"></script>    
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
   <!-- MAP & CONTACT -->
    <script src="../static/js/map.js"></script>

</body>
</html>

myapp/templates/login.html
{% extends "index.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        {{ form.username.label_tag }}
        {{ form.username }}
        {{ form.password.label_tag }}
        {{ form.password }}
        <button type="submit">Login</button>
    </form>
    {% endblock %}
</body>
</html>

myapp/templates/property_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ property.name }} Profile</title>
</head>
<body>
    <h1>{{ property.name }} - Property Profile</h1>
    <p><strong>Address:</strong> {{ property.address }}</p>
    <p><strong>Location:</strong> {{ property.location }}</p>
    <p><strong>Features:</strong> {{ property.features }}</p>

    <h2>Units:</h2>
    <ul>
        {% for unit in units %}
            <li>
                <strong>Type:</strong> {{ unit.get_unit_type_display }} |
                <strong>Rent Cost:</strong> ${{ unit.rent_cost }} |
                <strong>Tenants:</strong>
                {% for tenant in tenants %}
                    {% if tenant.unit == unit %}
                        {{ tenant.name }},
                    {% endif %}
                {% endfor %}
            </li>
        {% endfor %}
    </ul>
</body>
</html>

myapp/templates/tenant_management.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tenant Management</title>
</head>
<body>
    <h1>Tenant Management</h1>
    <ul>
        {% for tenant in tenants %}
            <li><a href="{% url 'tenant_profile' tenant.id %}">{{ tenant.name }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

myapp/templates/tenant_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ tenant.name }} Profile</title>
</head>
<body>
    <h1>{{ tenant.name }} - Tenant Profile</h1>
    <p><strong>Address:</strong> {{ tenant.address }}</p>
    <p><strong>Document Proofs:</strong> {{ tenant.document_proofs }}</p>
    <p><strong>Agreement End Date:</strong> {{ tenant.agreement_end_date }}</p>
    <p><strong>Monthly Rent Date:</strong> {{ tenant.monthly_rent_date }}</p>
</body>
</html>